config/routes.rb
Videotalksite::Application.routes.draw do

  resources :comments

  resources :videos do
    resources :comments
  end
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
             controllers: {:omniauth_callbacks => "omniauth_callbacks", registrations: "registrations"}
  root to: 'home#index'

  resource :users
  match '/profile' => "users#profile"
  match '/upload_avatar' => "users#upload_avatar"

  resources :videos, :except => :index
  resources :uploads, :only => :index

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/video.rb
class Video
  include Mongoid::Document
  field :path, :type => String
  field :status, :type => String, default: 'processing'
  field :upvote,:type => Integer
  mount_uploader :path, VideoUploader
  process_in_background :path
  embeds_many :comments, :as => :commentable
  def set_success(format, opts)
    set(:status, 'done')
  end

  def create_comment!(params)
    comment = comments.create!(params)
    comment.path = comment.parent ? comments.find(comment.parent).path + '.' + comment.id.to_s : "root."+comment.id.to_s
    comment
  end

  def comments_list(sort=:asc)
    if Comment.respond_to?(sort)
      comments.send(sort,:path)
    else
      raise ArgumentError, "Wrong argument!"
    end
  end

  def branch_for(comment_id)
    comments.select{|i| i.path =~ Regexp.new('^' + comments.find(comment_id).path)}
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])
    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :path %>
    <%= f.file_field :path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table>
  <tr>
    <th>Path</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @videos.each do |video| %>
  <tr>
    <td><%= video.path %></td>
    <td><%= link_to 'Show', video %></td>
    <td><%= link_to 'Edit', edit_video_path(video) %></td>
    <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.haml
%table.fixed-width.three-column.width-1180px#video
  %tbody
    %tr
      %td.width-200px
      %td
        - if @video.status == 'done'
          %video.sublime{:poster => "#{@video.path.screenshot}", :width => "640", :height => "360", :title => "Midnight Sun", 'data-uid' => "a240e92d", :preload => "none"}
            %source{:src => "#{@video.path.mp4}"}
        - else
          %div.processing
            %div.loading.size-96px
            %div.text Video is processing....
        %br
        %div.shared
          %img.size-36px.pointer{:src => '/assets/btn_facebook.png', 'data-type' => 'facebook'}
          %img.size-36px.pointer{:src => '/assets/btn_google.png', 'data-type' => 'google'}
          %img.size-36px.pointer{:src => '/assets/btn_twitter.png', 'data-type' => 'twitter'}
      %td.width-320px

%div.box-comment


%script{:type => "text/javascript"}
  window.router = new Voicetalk.Routers.VideosRouter({video: #{@video.to_json({:include => :comments}).html_safe} });
  Backbone.history.start();